/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { IApe, IApeInterface } from "../../../contracts/Factory.sol/IApe";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "name_",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol_",
        type: "string",
      },
      {
        internalType: "string",
        name: "uri_",
        type: "string",
      },
      {
        internalType: "address",
        name: "minter_",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IApe__factory {
  static readonly abi = _abi;
  static createInterface(): IApeInterface {
    return new utils.Interface(_abi) as IApeInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IApe {
    return new Contract(address, _abi, signerOrProvider) as IApe;
  }
}
