/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as erc721ASol from "./ERC721A.sol";
import type * as extensions from "./extensions";

export type { erc721ASol };

export type { extensions };
export type { IERC721A } from "./IERC721A";
