/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import * as Contracts from ".";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";
import { ethers } from "ethers";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "ERC721Enumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Enumerable__factory>;
    getContractFactory(
      name: "IERC721Enumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Enumerable__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "BridgedNervape",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BridgedNervape__factory>;
    getContractFactory(
      name: "CampaignMinter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CampaignMinter__factory>;
    getContractFactory(
      name: "Greeter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Greeter__factory>;
    getContractFactory(
      name: "GroupMinter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GroupMinter__factory>;
    getContractFactory(
      name: "INervape",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.INervape__factory>;
    getContractFactory(
      name: "MerkleWhitelist",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MerkleWhitelist__factory>;
    getContractFactory(
      name: "Nervape",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Nervape__factory>;
    getContractFactory(
      name: "NervapeCharacter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NervapeCharacter__factory>;
    getContractFactory(
      name: "NervapeFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NervapeFactory__factory>;
    getContractFactory(
      name: "Sample",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Sample__factory>;
    getContractFactory(
      name: "StoryVoting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StoryVoting__factory>;
    getContractFactory(
      name: "Whitelist",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Whitelist__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;
    getContractAt(
      name: "ERC721Enumerable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721Enumerable>;
    getContractAt(
      name: "IERC721Enumerable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Enumerable>;
    getContractAt(
      name: "IERC721Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Receiver>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "BridgedNervape",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BridgedNervape>;
    getContractAt(
      name: "CampaignMinter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CampaignMinter>;
    getContractAt(
      name: "Greeter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Greeter>;
    getContractAt(
      name: "GroupMinter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GroupMinter>;
    getContractAt(
      name: "INervape",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.INervape>;
    getContractAt(
      name: "MerkleWhitelist",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MerkleWhitelist>;
    getContractAt(
      name: "Nervape",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Nervape>;
    getContractAt(
      name: "NervapeCharacter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.NervapeCharacter>;
    getContractAt(
      name: "NervapeFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.NervapeFactory>;
    getContractAt(
      name: "Sample",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Sample>;
    getContractAt(
      name: "StoryVoting",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StoryVoting>;
    getContractAt(
      name: "Whitelist",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Whitelist>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
